<a href="https://colab.research.google.com/github/noahcoulson/mis433/blob/main/Copy_of_assignment_python_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment: Python Basics
We assume you are using Python 3 in this course.

## Question 1

You've learned different data types in Python. Now, let's test your knowledge.

You need to use to format strings.

Write a program using the "f-strings" (https://realpython.com/python-f-strings/) and user input function to convert temperatures from Fahrenheit to Celsius. [Formula: Celsius = (Fahrenheit – 32)*5/9]

Hint: you may need int() or float() function

An example program output:
```
Please enter the temperature in Fahrenheit: 140
140F is 60.0 in Celsius.
```

In [ ]:
# an example of f-strings and user input function
username = input('What\'s your name? ')
print(f'Welcome, {username}!')

In [ ]:
# complete your program here
f = input('Please enter the temperature in Fahrenheit: ')

print(f)

#Celsius = (Fahrenheit – 32)*5/9
c = (f - 32) * 5/9

print(f'{f}F is {c} in Celsius. ')
#print(str(f)+'F is '+str(c)+' in Celsius. ')

Now, do the oppsoite by convert temperatures from Celsius to Fahrenheit.
Another example:
```
Please enter the temperature in Celcius: 60
60C is 140.0 in Fahrenheit.
```

In [ ]:
# complete your program here
c = float(input('Please enter the temperature in Celsius'))

print(c)

f = (c * 1.8) + 32

print(str(c) + 'C is ' + str(f) +' in Fahrenheit. ')

Please enter the temperature in Celsius60
60.0
60.0C is 140.0 in Fahrenheit. 


Next, let's make it a bit challenging by adding conditional statements to convert temperatures to and from Celsius, Fahrenheit. [Formula: Celsius/5 = (Fahrenheit – 32)/9]

An example program output:
```
Please enter the temperature: 60
Is this in Celsius or Fahrenheit? C
60C is 140 in Fahrenheit
```

Another example:
```
Please enter the temperature: 140
Is this Celsius or Fahrenheit? F
140F is 60 in Celsius
```

In [ ]:
# complete your program here
d = input('Please enter the temperature: ')
m = input('Is this in Celsius or Fahrenheit? ')
d = float(d)

if m == 'C':
  f = (d * 1.8) + 32
  print(str(d) + 'C is ' + str(f) + ' in Fahrenheit. ')
else:
  c = (d - 32) * 5/9
  print(str(d) + 'F is ' + str(c) + ' in Celsius. ')

Please enter the temperature: 140
Is this in Celsius or Fahrenheit? F
140.0F is 60.0 in Celsius. 


## Question 2

Have some fun with strings.

In [ ]:
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

In [ ]:
# Find the length of this sentence.
sentence = "Talk is cheap. Show me the code - Linus Torvalds"
length = len(sentence)
print(length)

48


In [ ]:
# Convert the whole string to lower case.
lower = sentence.lower()
print(lower)

talk is cheap. show me the code - linus torvalds


In [ ]:
# Extract a substring from the 10th character from left to the 10th character from right.
substring = sentence[9:38]
print(substring)

heap. Show me the code - Linu


In [ ]:
# Split the sentence into a list of substrings by space ' '.
split = sentence.split(' ')
print(split)

['Talk', 'is', 'cheap.', 'Show', 'me', 'the', 'code', '-', 'Linus', 'Torvalds']


In [ ]:
# Given the sentence, output a list of words in lowercase (without punctuations).
print(sentence.lower().replace('-', '').split(' '))

['talk', 'is', 'cheap.', 'show', 'me', 'the', 'code', '', 'linus', 'torvalds']


In [ ]:
# Count the total number of vowels in the sentence.
vowels = ['a','e','i','o','u']
vowels = 'aeiou'
for v in vowels:
    count = 0
    for char in sentence.lower():
      if char in vowels:
          count+=1

print(count)

13


In [ ]:
# Find the positions (indexes) of all vowels in the sentence.
for i in range(len(sentence)):
    if sentence[i] in vowels:
      print(i)


1
5
10
11
17
21
25
28
30
35
37
41
44


## Question 3

Review list comprehension if needed: https://realpython.com/list-comprehension-python/

The formula for list comprehension is: `new_list = [expression for member in iterable (if conditional)]`

You need to do the following:

In [ ]:
# Use a loop to create a list of 5 cube numbers and print the list：[0, 1, 8, 27, 64]
cubes = []


In [ ]:
# Use list comprehension to create the same list
cubes = [x**3 for x in range(5)]
print(cubes)

[0, 1, 8, 27, 64]


In [ ]:
# Find the postions (indexes) of all vowels in a sentence using list comprehension
sentence = "Toto, I\'ve a feeling we\'re not in Kansas anymore. - THE WIZARD OF OZ (1939)"
vowels = 'aeiou'
vowel_index = [i for i, char in enumerate(sentence.lower()) if char in vowels]
print(vowel_index)

[1, 3, 6, 9, 11, 14, 15, 17, 22, 25, 28, 31, 35, 38, 41, 45, 47, 54, 57, 59, 63, 66]


In [ ]:
# Use a loop to create a list of first n numbers in the Fibonacci sequence
# [0, 1, 1, 2, 3, 5, 8, ...]
fibonacci = []
n = input('How many numbers do you want? ')
n = int(n)

# add your code here
for i in range(n):
  if i == 0:
        fibonacci.append(0)
  elif i == 1:
        fibonacci.append(1)
  else:
      next_val = fibonacci[-1] + fibonacci[-2]
      fibonacci.append(next_val)
print(fibonacci)

How many numbers do you want? 4
[0, 1, 1, 2]


## Question 4

This question is about Python dictionary.

|Vaccine|Efficacy|
|-----|-------|
|Pfizer|95%|
|Moderna|95%|
|AstraZeneca|72%|
|Johnson & Johnson|66%|

Source: https://www.biospace.com/article/comparing-covid-19-vaccines-pfizer-biontech-moderna-astrazeneca-oxford-j-and-j-russia-s-sputnik-v/

In [ ]:
# Create a dictionary to save the data of vaccines and their efficacy. (save 95% as 0.95)
v_dict = {'Pfizer': '0.95', 'Moderna': '0.95', 'AstraZeneca': '0.72',
          'Johnson & Johnson': '0.66'}

In [ ]:
v = input('Which vaccine? ')
# print the efficacy of the vaccine
print(v_dict.get(v))

Which vaccine? Pfizer
0.95


In [ ]:
# add another vaccine 'Sputnik V' with 91.4% efficacy rate to the dictionary
v_dict['Sputnik V'] = 0.914

In [ ]:
# add another vaccine 'Sinovac' with 50.38% efficacy rate to the dictionary
v_dict['Sinovac'] = 0.5038

In [ ]:
# Print vaccines with efficacy lower than 90%.
for i in v_dict:
    if float(v_dict[i]) < 0.9:
        print(i)

AstraZeneca
Johnson & Johnson


In [ ]:
# delete the Sinovac vaccine from the dictionary.
del v_dict['Sinovac']

In [ ]:
#Count the occurrence of each alphabet (no space ' ') in this sentence.
sentence = 'the quick brown fox jumps over the lazy dog'

# Save the result in a dictionary
ch_dict = {}
# Use a loop to iterate all characters
# add your code here
for char in sentence:
    if char != ' ':
        if char in ch_dict:
            ch_dict[char] += 1
        else:
            ch_dict[char] = 1
# print the dictionary
print(ch_dict)

{'t': 2, 'h': 2, 'e': 3, 'q': 1, 'u': 2, 'i': 1, 'c': 1, 'k': 1, 'b': 1, 'r': 2, 'o': 4, 'w': 1, 'n': 1, 'f': 1, 'x': 1, 'j': 1, 'm': 1, 'p': 1, 's': 1, 'v': 1, 'l': 1, 'a': 1, 'z': 1, 'y': 1, 'd': 1, 'g': 1}


## Quesion 5

Next, we will practice with Numpy arrays.  

In [ ]:
import numpy as np

In [ ]:
# create a 1-D array of first 20 positive even numbers (starting with 2)
np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [ ]:
# create a 1-D array of first 20 positive odd numbers (starting with 1)
np.array([1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39])

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [ ]:
# create a 10x10 array in the following format:
# first row: [0,1,...,9]
# second row: [10,11,...,19]
# ...
# tenth row: [90,91,...,99]
array10x10 = np.arange(100).reshape(10, 10)
print(array10x10)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [ ]:
# Create a 10x10 array of normally distributed random values
# with mean 0 and standard deviation 1
M = np.random.normal(0, 1, (10,10))
M.shape
print(M)

[[-1.2344147  -0.90711963  0.35544651 -0.5144097  -1.79509971  0.57023188
  -0.88292282 -0.39520176 -0.17504144  0.25200094]
 [ 1.21375493 -0.45382984  0.47643839  0.9920517  -0.73595343 -0.01218536
  -0.3341196  -0.59931763 -0.62042817  0.59635022]
 [-0.9649136   1.19920813 -0.30541682  0.25415918  1.15588276  0.28436323
  -0.17868228 -0.55071697  0.08045959  0.48994692]
 [ 0.37400695 -0.03637036 -0.96181033 -0.75882425  0.55838999  1.19790985
  -1.05752577  0.10886079  0.7206432   0.6872813 ]
 [-0.44846704  0.44156006  0.06952056  0.31183592  0.81703857 -0.12680218
  -1.4633481   1.00207748  1.22730338 -0.03043577]
 [-1.22626967 -0.22770301  0.83723045  0.66426009 -1.52600326  1.95124742
   0.96526687  0.63341421 -0.27509193  0.97383366]
 [-0.25170997  0.21610492  1.00513929 -0.90236455 -0.55403356 -0.9915853
   0.92515809  0.5624769   0.24807537 -1.13331261]
 [ 0.00888467  0.0884354   0.21188648 -0.38895673 -0.4286254  -0.10001904
  -2.66899649 -1.48743116  1.56198683 -0.76601152]
 

In [ ]:
# Count the numbers in M with an absolute value greater than 1.
for i in M:
    for j in i:
        if abs(j) > 1:
            print(j)

-1.234414704458106
-1.7950997126347041
1.2137549260648988
1.1992081332304867
1.1558827578794886
1.1979098482074884
-1.0575257651882588
-1.4633480960084562
1.002077476999283
1.2273033761061785
-1.2262696699979245
-1.5260032589829136
1.9512474177761265
1.0051392930984686
-1.133312614220618
-2.668996491455268
-1.4874311637484727
1.5619868253130427
1.3612602673441059
1.3350815348596528
-1.519240962566718
1.144557997768735
-1.339771645979313
-2.0648902988805418
1.4130766426715264
-1.6743960028700597
1.309888220337073


In [ ]:
# Reference: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

# Input the number of rows (input an integer >= 3)
r = input('Row count: ')
r = int(r)
# Input the number of rows (input another integer >= 3)
c = input('column count: ')
c = int(c)
# Hint: you may want to use the function int().

# Create a r x c array of random integers between 10 (inclusive) and 20 (exclusive).
arr = np.random.randint(10, 20, (r, c))
arr

Row count: 4
column count: 5


array([[13, 13, 15, 18, 12],
       [18, 11, 13, 15, 18],
       [19, 18, 19, 19, 13],
       [19, 14, 14, 17, 10]])

In [ ]:
# output the element in the first row and the third column
print(arr[0, 2])

15


In [ ]:
# output the element in the second row and the last column
print(arr[1, 4])

18


In [ ]:
# output the second row of the array
print(arr[1])

[18 11 13 15 18]


In [ ]:
# output the second last row of the array
print(arr[2])

In [ ]:
# output the second column of the array
print(arr[:, 1])

[13 11 18 14]


In [ ]:
# output the second last column of the array
print(arr[:, 3])

[18 15 19 17]


In [ ]:
# output the upper-left 3x3 sub-array
print(arr[0:3, 0:3])

[[13 13 15]
 [18 11 13]
 [19 18 19]]


In [ ]:
# output the bottom-left 3x3 sub-array
print(arr[-3:, :3])

[[18 11 13]
 [19 18 19]
 [19 14 14]]


In [ ]:
# output the upper-right 3x3 sub-array
print(arr[0:3, -3:])

[[15 18 12]
 [13 15 18]
 [19 19 13]]


In [ ]:
print(arr[-3:, -3:])

[[13 15 18]
 [19 19 13]
 [14 17 10]]


In [ ]:
A = np.arange(1, 51)
A = A.reshape(5, 10)
print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


In [ ]:
A = np.vstack([A, np.arange(51, 61)])
print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [ ]:
# split the new A (6x10) to two 3x10 arrays A1 and A2
A1, A2 = np.split(A, [3])
print(A1)
print(A2)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [ ]:
A = np.add(A, 10)
print(A)

[[11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]
 [61 62 63 64 65 66 67 68 69 70]]


In [ ]:
# Calculate the square root of each element in A
A = np.sqrt(A)
print(A)

[[3.31662479 3.46410162 3.60555128 3.74165739 3.87298335 4.
  4.12310563 4.24264069 4.35889894 4.47213595]
 [4.58257569 4.69041576 4.79583152 4.89897949 5.         5.09901951
  5.19615242 5.29150262 5.38516481 5.47722558]
 [5.56776436 5.65685425 5.74456265 5.83095189 5.91607978 6.
  6.08276253 6.164414   6.244998   6.32455532]
 [6.40312424 6.4807407  6.55743852 6.63324958 6.70820393 6.78232998
  6.8556546  6.92820323 7.         7.07106781]
 [7.14142843 7.21110255 7.28010989 7.34846923 7.41619849 7.48331477
  7.54983444 7.61577311 7.68114575 7.74596669]
 [7.81024968 7.87400787 7.93725393 8.         8.06225775 8.1240384
  8.18535277 8.24621125 8.30662386 8.36660027]]


In [ ]:
# Above, we have created a 10x10 array M of normally distributed random values
# with mean 0 and standard deviation 1
M.shape

(10, 10)

In [ ]:
# Print the mean, standard devietion of all numbers in M
M = np.mean(M)
print(M)
M = np.std(M)
print(M)

0.022124579543610027
0.0


In [ ]:
# Print the maximumn, 3rd quartile, median, 1st quartile, and minimum in M
M = np.max(M)
print(M)
M = np.min(M)
print(M)
M = np.median(M)
print(M)

0.0
0.0
0.0
